[package]
name = "site"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-latex = { path = "../" }
leptos = { version = "0.6.12", features = ["csr"] }
console_log = "1"
log = "0.4"
console_error_panic_hook = "0.1.7"
