name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract version from tag
        run: |
          VERSION=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')
          echo "VERSION={$VERSION#v}" >> $GITHUB_ENV
      - name: Get Changelog
        run: |
          changelog=$(grep -A 1000 "^## \[$VERSION\]" CHANGELOG.md | sed '1d;/^## \[/,$d')
          echo "RELEASE_NOTES=$changelog" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ env.RELEASE_NOTES }}
          files: |
            styles.css
            font/
          generate_release_notes: true
